import AppKit
import SwiftUI

/// Dot 5: the last ten things you copied (three without Dots Pro), shown as cards over the screen (ClipboardOverlay.swift). Kept between
/// launches in Application Support (see ClipboardStore); passwords and other copies an app marks
/// concealed or transient are never recorded.
///
/// Reading the clipboard without the user pasting shows a system alert on every read, so history
/// is only recorded silently once Dots is set to "Always Allow" in System Settings › Privacy &
/// Security › Paste from Other Apps. Watching `changeCount` never reads, so it's always quiet.
/// Until then, opening the card reads once (showing the alert) and explains the setting.
@MainActor
final class ClipboardHistory: ObservableObject {
    struct Item: Identifiable, Equatable {
        enum Content: Equatable {
            case text(String)
            case image(NSImage)
        }

        let id: UUID
        let content: Content
        let copiedAt: Date

        init(id: UUID = UUID(), content: Content, copiedAt: Date = Date()) {
            self.id = id
            self.content = content
            self.copiedAt = copiedAt
        }
    }

    static let limit = 10
    private static let pollInterval: TimeInterval = 0.5

    @Published private(set) var items: [Item] {
        didSet { store.save(items) }
    }
    @Published private(set) var needsPermission = false

    /// All ten are always kept; without Dots Pro only the newest three are shown and copyable.
    var visibleItems: [Item] {
        ProStore.shared.isPro ? items : Array(items.prefix(ProStore.freeClipboardLimit))
    }

    private let store = ClipboardStore()
    private let pasteboard = NSPasteboard.general
    private var lastChange = NSPasteboard.general.changeCount
    private var poll: Timer?

    init() {
        items = store.load()
    }

    private var canReadSilently: Bool {
        if #available(macOS 15.4, *) { return pasteboard.accessBehavior == .alwaysAllow }
        return true
    }

    /// Runs while the clipboard dot is enabled.
    func setWatching(_ isOn: Bool) {
        poll?.invalidate()
        poll = nil
        guard isOn else { return }
        lastChange = pasteboard.changeCount
        poll = Timer.scheduledTimer(withTimeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.checkForChange() }
        }
    }

    /// When the card opens: pick up the current clipboard even if it can't be read silently
    /// (opening the card is the user asking for it).
    func refresh() {
        if !canReadSilently {
            needsPermission = true
            capture()
            lastChange = pasteboard.changeCount
        }
    }

    func copy(_ item: Item) {
        pasteboard.clearContents()
        switch item.content {
        case .text(let text): pasteboard.setString(text, forType: .string)
        case .image(let image): pasteboard.writeObjects([image])
        }
        // Our own write: don't record it again, just move it to the top (one change, one save).
        lastChange = pasteboard.changeCount
        var moved = items.filter { $0.id != item.id }
        moved.insert(item, at: 0)
        items = moved
    }

    func delete(_ item: Item) {
        items.removeAll { $0.id == item.id }
    }

    func openPrivacySettings() {
        if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy") {
            NSWorkspace.shared.open(url)
        }
    }

    private func checkForChange() {
        let change = pasteboard.changeCount
        guard change != lastChange else { return }
        lastChange = change
        needsPermission = !canReadSilently
        if !needsPermission { capture() }
    }

    /// Password managers and the like mark what shouldn't be kept (nspasteboard.org).
    private static let privateTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private func capture() {
        if let types = pasteboard.types, !Self.privateTypes.isDisjoint(with: types) { return }
        let content: Item.Content
        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            content = .text(text)
        } else if let image = NSImage(pasteboard: pasteboard) {
            content = .image(image)
        } else {
            return
        }
        // Copying the same thing again just brings it to the top; built aside so it's one save.
        var updated = items.filter { $0.content != content }
        updated.insert(Item(content: content), at: 0)
        items = Array(updated.prefix(Self.limit))
    }
}

/// Keeps the clipboard history between launches: an index as JSON and each image as a PNG, in
/// Application Support/Dots/Clipboard. All file work (and turning images into PNGs) happens off the
/// main thread, in order.
@MainActor
final class ClipboardStore {
    private struct Entry: Codable {
        var id: UUID
        var text: String?
        var copiedAt: Date
    }

    /// An image handed to the store's queue; it's only read there, never changed.
    private struct Pending: @unchecked Sendable {
        let url: URL
        let image: NSImage
    }

    private let directory: URL
    private let queue = DispatchQueue(label: "app.dots.clipboard-store", qos: .utility)
    /// Items whose PNG has been (or is queued to be) written. Kept here rather than checked on disk,
    /// so a save queued right after another never mistakes a file that's about to go for one to keep.
    private var written = Set<UUID>()

    init() {
        let support = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        directory = support.appendingPathComponent("Dots/Clipboard", isDirectory: true)
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
    }

    private var indexURL: URL { directory.appendingPathComponent("items.json") }

    private func imageURL(for id: UUID) -> URL {
        directory.appendingPathComponent("\(id.uuidString).png")
    }

    func load() -> [ClipboardHistory.Item] {
        guard let data = try? Data(contentsOf: indexURL),
              let entries = try? JSONDecoder().decode([Entry].self, from: data) else { return [] }
        return entries.compactMap { entry in
            if let text = entry.text {
                return ClipboardHistory.Item(id: entry.id, content: .text(text), copiedAt: entry.copiedAt)
            }
            guard let image = NSImage(contentsOf: imageURL(for: entry.id)) else { return nil }
            written.insert(entry.id)
            return ClipboardHistory.Item(id: entry.id, content: .image(image), copiedAt: entry.copiedAt)
        }
    }

    func save(_ items: [ClipboardHistory.Item]) {
        var entries: [Entry] = []
        var newImages: [Pending] = []
        var imageIDs = Set<UUID>()
        for item in items {
            switch item.content {
            case .text(let text):
                entries.append(Entry(id: item.id, text: text, copiedAt: item.copiedAt))
            case .image(let image):
                entries.append(Entry(id: item.id, copiedAt: item.copiedAt))
                imageIDs.insert(item.id)
                // An item's image never changes, so it's written once.
                if !written.contains(item.id) { newImages.append(Pending(url: imageURL(for: item.id), image: image)) }
            }
        }
        written = imageIDs
        let keep = Set(imageIDs.map { imageURL(for: $0).lastPathComponent })
        let directory = directory, indexURL = indexURL
        queue.async {
            for pending in newImages {
                let png = pending.image.tiffRepresentation
                    .flatMap(NSBitmapImageRep.init(data:))?
                    .representation(using: .png, properties: [:])
                try? png?.write(to: pending.url, options: .atomic)
            }
            if let data = try? JSONEncoder().encode(entries) { try? data.write(to: indexURL, options: .atomic) }
            // Images of items that have dropped off the end.
            let files = (try? FileManager.default.contentsOfDirectory(atPath: directory.path)) ?? []
            for file in files where file.hasSuffix(".png") && !keep.contains(file) {
                try? FileManager.default.removeItem(at: directory.appendingPathComponent(file))
            }
        }
    }
}
